- scirpy/datasets/__init__.py
> Update dataset urls to files hosted on Github

- README.rst
> Add Bioconda installation instructions.

- .github/workflows/docs.yml
> Build docs for branches, tags and pulls. 

- docs/tutorials/tutorial_3k_tcr.md
- scirpy/_tools/_clonotypes.py
- tests/fixtures.py
- tests/test_clonotypes.py
> Add option to take v gene into account during clonotype definition

- docs/api.rst
- docs/glossary.rst
- docs/tcr-biology.rst
- docs/tutorials/tutorial_3k_tcr.md
- docs/tutorials/tutorial_io.md
- scirpy/_plotting/_clonotypes.py
- scirpy/_tools/__init__.py
- scirpy/_tools/_clonotypes.py
- scirpy/tcr_dist/__init__.py
- tests/fixtures.py
- tests/test_clonotypes.py
- tests/test_tcr_dist.py
> Differentiate between clonotypes and clonotype clusters

- scirpy/_plotting/_repertoire_overlap.py
> Fix reordering of row annotations on repertoire overlap heatmap

- docs/api.rst
- docs/conf.py
- docs/glossary.rst
- docs/references.bib
- scirpy/_tools/__init__.py
- scirpy/_tools/_convergence.py
- tests/fixtures.py
- tests/test_clonotypes.py
> Add tool identifying convergent evolution of clonotypes

- pyproject.toml
- scirpy/datasets/__init__.py
This has been fixed in scanpy upstream in 1.6.0
(https://github.com/theislab/scanpy/pull/1130). Removing
the patch and requiring scanpy>=1.6.0.
> Remove tqdm monkey patch.

- docs/tutorials/tutorial_3k_tcr.md
- scirpy/_plotting/_vdj_usage.py
- scirpy/tests/test_plotting.py
> Fix vdj_usage plot

- scirpy/_tools/_clonal_expansion.py
- scirpy/_tools/_convergence.py
- scirpy/tests/fixtures.py
- scirpy/tests/test_clonotypes.py
- scirpy/tests/test_tools.py
> Ensure that clonal_expansion does not count 'nan's

- .github/workflows/test.yml
- docs/api.rst
- docs/glossary.rst
- docs/tutorials/tutorial_3k_tcr.md
- docs/tutorials/tutorial_io.md
- docs/usage-principles.rst
- scirpy/io/_io.py
- scirpy/io/_util.py
> Update documentation to reflect changes to IO module

- pyproject.toml
- scirpy/io/_convert_anndata.py
- scirpy/io/_io.py
- scirpy/tests/test_io.py
> Pin anndata v0.7.6 and fix issue with saving adata object

- docs/index.rst
- docs/versions.rst
- scirpy/_tools/_clonotypes.py
- scirpy/ir_dist/_clonotype_neighbors.py
- scirpy/tests/test_workflow.py
> Add dynamic version information to docs

- .github/workflows/docs.yml
- docs/tutorials/tutorial_3k_tcr.md
- pyproject.toml
- scirpy/_plotting/_diversity.py
- scirpy/_tools/_diversity.py
- scirpy/tests/test_tools.py
> add diversity metrics 07022021

- scirpy/io/_io.py
- scirpy/tests/test_io.py
> Improve infer_locus_from_gene_name

- docs/api.rst
- docs/references.bib
- docs/tutorials/tutorial_3k_tcr.md
- pyproject.toml
- scirpy/datasets/__init__.py
- scirpy/datasets/_processing_scripts/.gitignore
- scirpy/ir_dist/__init__.py
- scirpy/ir_dist/_clonotype_neighbors.py
- scirpy/ir_dist/_util.py
- scirpy/ir_dist/metrics.py
- scirpy/pl/styling.py
- scirpy/tests/fixtures.py
- scirpy/tests/test_ir_dist.py
- scirpy/tests/test_ir_dist_util.py
- scirpy/tests/test_ir_query.py
- scirpy/tests/test_workflow.py
- scirpy/tl/__init__.py
- scirpy/tl/_clonotype_modularity.py
- scirpy/tl/_clonotypes.py
- scirpy/tl/_ir_query.py
- scirpy/tl/_query_epitopes.py
- scirpy/util/__init__.py
> Query epitope databases

- pyproject.toml
> fix: resolved dependency clash

- pyproject.toml
- scirpy/tests/test_io.py
> Update minimal dandelion version

- docs/api.rst
- docs/references.bib
- scirpy/datasets/__init__.py
- scirpy/io/_io.py
I added a function to download data from the IEDB and process it into an AnnData object. This can be used as an additional epitope database for the query function.
> Download IEDB and process it into an AnnData object

- .conda/meta.yaml
- scirpy/pp/_index_chains.py
Close #386
- update conda test dependencies
- speed up index_chains
> Speed up index_chains

- CHANGELOG.md
> Fix usage of wrong column in 3k tutorial

- .conda/meta.yaml
- .github/workflows/conda.yaml
> Fix conda ci

- CHANGELOG.md
> Update changelog for v0.16

- CHANGELOG.md
- src/scirpy/tl/_diversity.py
> Update D50 docstring

- .gitignore
> Remove data directory (was accidentically committed)

- CHANGELOG.md
- src/scirpy/pl/_clonotypes.py
- src/scirpy/tests/conftest.py
- src/scirpy/tests/test_plotting.py
- src/scirpy/tl/_clonotypes.py
> Fix that pl.clonotype_network couldn't use non-standard obsm key

- .github/workflows/test.yaml
- CHANGELOG.md
- pyproject.toml
> Add optional dependencies to [test]

- src/scirpy/get/__init__.py
> Fix _has_ir AwkwardArrayView edgecase

- CHANGELOG.md
- pyproject.toml
> Unpin anndata

- src/scirpy/pp/_index_chains.py
> Fix index_chains method description

- .gitignore
- CHANGELOG.md
- src/scirpy/datasets/__init__.py
Close #577 
Close #576 
Close #575
> Fix incompatibility with latest vdjdb release

- docs/contributing.md
> Update publishing workflow docs

- .github/workflows/test.yaml
- pyproject.toml
> Don't run GPU CI by default

- CHANGELOG.md
- docs/data-structure.rst
> Fix code snippet to merge anndata objects

- CHANGELOG.md
- src/scirpy/datasets/__init__.py
> Switch exampledata to scverse s3 bucket instead of figshare

- CHANGELOG.md
> bump changelog version
