docs/tutorials/tutorial_3k_tcr.md
pyproject.toml
scirpy/_plotting/_repertoire_overlap.py
scirpy/_tools/_clonal_expansion.py
scirpy/_tools/_clonotypes.py
scirpy/_tools/_diversity.py
scirpy/_tools/_group_abundance.py
scirpy/_tools/_repertoire_overlap.py

- alpha diversity had an issue with pandas > 1
- minimal version requirements for anndata and scanpy are now implemented (#111)
- fixed pandas future warning in `group_abundance`
- use `groupby(observed=True)` wherever applicable.

Compatibility fixes

---

pyproject.toml
scirpy/tcr_dist/__init__.py
tests/test_tcr_dist.py

Closes #165.
Before, tcr_dist could only compute a square distance matrix.
However, it can be useful to compute the distance against
another array of sequences, e.g. a CDR3 reference database.
This PR enables tcr_dist to compute a rectangular seqs1 x seqs2
distance matrix in addition to the square distance matrix.

Adapt tcr_dist to support second array of sequences

---

docs/api.rst
scirpy/tcr_dist/__init__.py
tests/test_tcr_dist.py

Introduces a new abstract base class ParallelDistanceCalculator
which calculates distances block-wise in parallel.
This has the advantage that only a small subset of sequences needs to be
transferred to the worker process, reducing the communication overhead
and speeding up the overall computation.
Fixes #170. 
Towards #53.

Optimize parallel sequence distance calculation. 

---

.conda/meta.yaml
.editorconfig
.github/workflows/conda.yml
.github/workflows/docs.yml
.github/workflows/pythonpublish.yml
.github/workflows/test.yml
.gitignore
docs/Makefile
docs/conf.py
pyproject.toml
scirpy/__init__.py
scirpy/_compat.py
scirpy/_metadata.py
workspace.code-workspace

Closes #178 
1) Switch from `get_version` to `setuptools_scm` which is more stable
2) Implement the changes `@ flyingsheep` proposed for scanpy
(https://github.com/theislab/scanpy/pull/1374/,
https://github.com/theislab/scanpy/pull/1376/). This cleans up some
redundancies and imports the package dependencies only
at run time, not at build time.

Improve packaging

---

.github/workflows/pythonpublish.yml

This allows me to create data releases independent of the versioned releases

Only run release action on vX.X.X tags

---

.github/workflows/conda.yml
.github/workflows/docs.yml
docs/api.rst
pyproject.toml
scirpy/_tools/_clonotypes.py
scirpy/ir_dist/__init__.py
scirpy/tests/test_tcr_dist.py

Figured that rather than make an issue asking for a thing I'd tried to implement the thing myself, to mixed results.
I have consulted with an immunologist with regards to BCR clonotype calling, and apparently somatic hypermutation only leads to substitution events. As such, an appropriate way to identify neighbours would be to require sequence length compatibility, and then use Hamming distance to identify substitutions. Going into your source code, the logic for the Levenshtein distance was clear:
result = []
for (row, s1), (col, s2) in coord_iterator:
d = levenshtein_dist(s1, s2)
if d <= self.cutoff:
result.append((d + 1, origin_row + row, origin_col + col))
As such, I replicated it for the Hamming distance plus sequence length, and added references to it wherever Levenshtein cropped …

Immunologist-approved BCR similarity measure implementation attempt

---

.conda/meta.yaml
.github/workflows/conda.yml
.github/workflows/docs.yml
.github/workflows/pythonpublish.yml
.github/workflows/test.yml
README.rst
pyproject.toml

Include Python 3.9 in tests. Drop support for 3.6.

---

.github/workflows/docs.yml

CI skipped the docs deploy step due to the wrong python version specified.

Fix deploy docs

---

docs/references.bib
scirpy/io/_datastructures.py
scirpy/io/_io.py

Hi @grst,
I'm adding some updates to dandelion's parser and came across a small issue and wondering if you could give me a hand.
I've made a small snippet of the all_contig_annotations.json file from 10x's resource to use as a fixture (attached as 'data.txt' here because github doesn't allow me to attach with .json extension):
[data.txt](https://github.com/icbi-lab/scirpy/files/6823960/data.txt)
The following round tripping works:
```python
import dandelion as ddl
import scirpy as ir
adata = ir.io.read_10x_vdj('data.json')
vdj = ddl.read_10x_vdj('data.json') # I've wrote a new parser for dandelion
vdj_1 = ir.io.to_dandelion(adata)
adata_1 = ddl.to_scirpy(vdj) # this basically calls ir.io.from_dandelion
adata_2 = ir.io.from_dandelion(vdj)
vdj_2 = ddl.from_scirpy(adata) # this basically …
```

adjusting add_serialized_chains behaviour

---

scirpy/_preprocessing/_merge_adata.py
scirpy/io/_datastructures.py

1. When include_fields=None, the multi_chain value has not been
transferred properly to adata.obs, as it had been overwritten.
Rearranged the order of statements to fix it. This prevented
bug 2 to surface.
2. Empty Airr cells got initialized with multi_chain=False. This
led to a conflict due to 'inconsistent cell-level attributes'
as soon as chains got added, even if all added chains correctly
had multi_chain=True. Now set it to None initially, as None
gets ignored when merging cell-level attributes.

Fix issues with AirrCell

---

.conda/meta.yaml
CONTRIBUTING.md
README.rst
docs/versions.rst
pyproject.toml

- Scverse rebranding
- Update black version
- pin sphinx version
- Fix autodoc-typehints
- matplotlib intersphinx
- Undo accidental markdown autoformat
- Temporarily ignore sphinx warnings
- Replace scverse.github.io with scverse.org

Fix docs links

---

.github/workflows/test.yml

This helps us catch failures due to upgraded dependencies

Run tests weekly

---

scirpy/datasets/__init__.py
scirpy/tests/test_datasets.py

Despite sticking to v3 version number, IEDB have updated their file format
* BCR and TCR are now in separate files
* the csv header has changed. Names are different, and there are now *two* rows
representing the header.
Close #389

Add tests for databases and fix IEDB

---

pyproject.toml

Please see https://github.com/igraph/python-igraph/issues/699 for the explanation.

dependencies: change python-igraph to igraph

---

CHANGELOG.md
docs/conf.py
src/scirpy/ir_dist/_clonotype_neighbors.py
src/scirpy/tl/_clonotypes.py
src/scirpy/tl/_ir_query.py

Retreive within_group from mdata OR adata

---

CHANGELOG.md
pyproject.toml
src/scirpy/pl/_clonotype_modularity.py

Fix incompatibility with adjustText 1.0

---

CHANGELOG.md
docs/conf.py
pyproject.toml
src/scirpy/io/_datastructures.py
src/scirpy/io/_io.py
src/scirpy/io/_util.py
src/scirpy/ir_dist/__init__.py
src/scirpy/ir_dist/metrics.py
src/scirpy/tests/test_ir_dist.py
src/scirpy/tests/test_ir_dist_metrics.py
src/scirpy/tl/_ir_query.py
src/scirpy/util/__init__.py

Closes #468
-   [x] Tests added (For bug fixes or new features)
-   [x] test and compare performance with old implementation and full wu2020 dataset.

Improve parallelism of ir_dist

---

CHANGELOG.md
src/scirpy/ir_dist/__init__.py
src/scirpy/ir_dist/_clonotype_neighbors.py
src/scirpy/ir_dist/metrics.py
src/scirpy/tests/test_ir_dist.py
src/scirpy/tl/_clonotype_modularity.py
src/scirpy/tl/_clonotypes.py
src/scirpy/tl/_ir_query.py

- Fix paralellization in ir_query
- Update docstrings
Closes #497 

Fix n_jobs behavior

---

CHANGELOG.md
src/scirpy/tests/test_util.py
src/scirpy/util/__init__.py
src/scirpy/util/graph/__init__.py

Closes #501 
-   [x] Tests added (For bug fixes or new features)

Fix set_obs throwing ValueError when Series aligns to MuData.

---

CHANGELOG.md
docs/api.rst
src/scirpy/datasets/__init__.py

Add Stephenson datasets

---

.github/workflows/test-gpu.yaml
CHANGELOG.md
src/scirpy/pl/_repertoire_overlap.py

fixing issue https://github.com/scverse/scirpy/issues/598 . To pass `**kwargs` parameters to customize the clustermap visualization when the `heatmap_cats` parameter is not used.

fix: missing **kwargs in clustermap call

---

CHANGELOG.md
src/scirpy/io/_io.py

Previously, full nt or aa tcr sequences from 10x contigs are not being read in by `read_10x_vdj`. This PR adds those attributes when read from 10x json output.

add sequence read in for 10x json
